name: socialmedia
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.8.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: null
  fluttertoast: ^8.2.2
  google_sign_in: ^6.1.4
  image_cropper:
  image_picker: ^1.0.1
  pandabar: ^0.1.2
  provider: ^6.0.5

dev_dependencies:
  build_runner: any
  equatable: ^2.0.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
